features:
  - KnowledgeTag
  - user_correct_answer
  - user_total_answer
  - user_acc
  - test_mean
  - test_sum
  - tag_mean
  - tag_sum
  - assessmentNum
  - userSolvedCnt
  - repeatCnt
  - tagExposureCnt
  - testNum
  - testType
  - month
  - hour
  - dayOfWeek
  - solvingTime
  - userLatentFactor1
  - userLatentFactor2
  - userLatentFactor3
  - assessmentLatentFactor1
  - assessmentLatentFactor2
  - assessmentLatentFactor3

contain_repeat_cnt: True
fill_nan: 0
type: 'second'