features:
# original
  - KnowledgeTag
# memory.py
  - user_acc
  - user_item_acc
  - user_tag1_acc
  - user_tag2_acc
  - user_last_tag1_correct
  - user_last_tag2_correct
# solving_time.py
  - solving_time
# assessments.py
  - assessment_num
  - user_solved_cnt
  - repeat_cnt
# tags.py
  - tag_exposure_cnt
# tests.py
  - test_type
  - test_num
# timepstamps.py
  - day_of_week
  - month
  - hour
# option
contain_repeat_cnt: True
fill_nan: 0
type: 'second'