# 학습에 포함시킬 feature 리스트
features:
# original
  - KnowledgeTag
# derived
  - UserAcc
  - UserTag1Acc
  - UserTag2Acc
  - UserLastTag1Correct
  - UserLastTag2Correct
  - ItemNumScaled
  - Tag1Acc
  - Tag2Acc
  - UserTestRetakeCnt
  - Tag2
  - UserRecency1
  - UserRecency2
  - UserRecency3
  - UserRecency4
  - UserRecency5
