# 학습에 포함시킬 feature 리스트
features:
# original
  - KnowledgeTag
# derived
  - UserAcc
  - UserTag1Acc
  - UserTag2Acc
  - UserLastTag1Correct
  - UserLastTag2Correct
  - ItemNumScaled
  - UserTestRetakeCnt
  - Tag2
  - UserRecency1
  - UserRecency2
  - UserRecency3
  - UserRecency4
  - UserRecency5
  - UserSolveCnt
  - RollingTime
  - UserInteraction1
  - UserInteraction2
  - UserInteraction3
  - UserInteraction4
  - UserInteraction5
  - UserTag1Interaction1
  - UserTag1Interaction2
  - UserTag1Interaction3
  - UserTag1Interaction4
  - UserTag1Interaction5
  - UserTag2Interaction1
  - UserTag2Interaction2
  - UserTag2Interaction3
  - UserTag2Interaction4
  - UserTag2Interaction5
