# sweep/default.yaml example
project: DKT_Sequential
entity: recsys01
program: main.py
method: grid
metric:
  goal: maximize
  name: val_auc
parameters:
  model:
    values: [GPT2]
  trainer.epoch:
    values: [100]
  trainer.lr:
    values: [0.001]
  trainer.weight_decay:
    values: [0.0001]

  
  data.augmentation:
    values: [True]
  data.stride:
    values: [15]
  data.max_seq_len:
    values: [20]

command:
- ${env}
- ${interpreter}
- ${program}
- ${args_no_hyphens}