# sweep/default.yaml example
project: DKT_Sequential
entity: recsys01
program: main.py
method: grid
metric:
  goal: maximize
  name: val_auc
parameters:
  model:
    values: [LSTM, LSTMATTN, BERT, SAINT_PLUS]
  trainer.epoch:
    values: [10, 20, 30]
  data.augmentation:
    values: [True]
  data.stride:
    values: [100]
  data.max_seq_len:
    values: [100]

command:
- ${env}
- ${interpreter}
- ${program}
- ${args_no_hyphens}
