project: DKT
entity: recsys01
program: main.py
method: grid
metric:
  goal: maximize
  name: cv_score
parameters:
  features:
    values: [default, comb1]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
