# spercify here default configurations
defaults:
  - _self_
  - features: default.yaml
  - model: LGBM.yaml
  - paths: default.yaml
  - wandb: default.yaml

data_version: 

skip_data_processing: False

is_submit: True

cv_strategy: kfold

k: 5

seed: 42

timestamp:
