# spercify here default configurations
defaults:
  - _self_
  - features: test.yaml
  - model: LGBM.yaml
  - paths: test.yaml
  - wandb: default.yaml

data_version: False

skip_data_processing: False

is_submit: True

cv_strategy: kfold

seed: 42

timestamp:
