project: DKT_Graph
entity: recsys01
program: main.py
method: grid
metric:
  goal: maximize
  name: val_acc
parameters:
  model.emb_dim: 
    values: [64, 128, 256]
  model.n_layers:
    values: [2,3,4]
  trainer.epoch:
    values: [10]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}

