project: DKT_Graph
entity: recsys01
program: main.py
method: grid
metric:
  goal: maximize
  name: val_acc
parameters:
  model.emb_dim: 
    values: [128]
  model.n_layers:
    values: [2]
  trainer.epoch:
    values: [1000]
  trainer.lr:
    values: [0.001]
  trainer.patience:
    values: [10]
  data.train_batch_size:
    values: [512, 1024, 2048, 4096]
  

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}

