name: LGBM

params:
  objective: binary
  metric:
    - auc
    - accuracy
  learning_rate: 0.1
  num_iterations: 1000
  boosting: gbdt
  max_depth: -1
  num_leaves: 31
  min_data_in_leaf: 20
  max_bin: 255
  feature_fraction: 1.0
  bagging_freq: 0
  bagging_fraction: 1.0

