# seed number
seed: 42

# train test split size
test_size: 0.5

# file path for ensemble
ensemble_path: _candidates/

# save path of final predict 
output_path: _finals/



# ensemble file list
ensemble_list: [
  dummy1,
  dummy2
]

# ensemble strategy (weighted/average/mixed/stacking)
ensemble: weighted

weight: [
  0.5,
  0.5
]

# cv strategy (holdout/kfold)
cv_strategy: kfold

# k of kfold
k: 5

# fit_intercept option of Linear Regression model
intercept_opt: True



# wandb project title
wandb_project: DKT_ensemble

# wandb entity 
wandb_entity: recsys01

# wandb work name
wandb_name: