# seed number
seed: 42

# train test split size
test_size: 0.5

# file path for ensemble
ensemble_path: _candidates/

# save path of final predict 
output_path: _finals/

# ensemble file list
ensemble_list: [
  dummy1,
  dummy2
]

# cv strategy (holdout/k-fold)
cv_strategy: holdout

# k of k-fold
k: 5

# wandb project title
wandb_project: DKT_ensemble

# wandb entity 
wandb_entity: recsys01

# wandb work name
wandb_name: