# path to data directory
data_path: /opt/ml/input/data/
# path to asset directory
asset_path: asset/
# path to output directory
output_path: outputs/

# name of train file
train_file: train_data.csv
# name of test file
test_file: test_data.csv